### PR TITLE
Release/0.5.1

### PR DESCRIPTION
**Pull request by ywkim312**
Updated library dependecies.

### CODE REVIEW

**Review by longshuicy — APPROVED** [review]

**Comment by navarroc** [comment]
Why is this pointing at develop and not main?

**Comment by ywkim312** [comment]
> Why is this pointing at develop and not main?

oops sorry about that. fixed

**Review by navarroc — APPROVED** [review]
Tested installation of pyincore/pyincore-viz/pyincore-data rc's together and ran a few testbed notebooks to verify. No issues found.

**Comment by navarroc** [comment]
Any idea why the pytest is taking so long to install it's dependencies? Seems stuck.

**Comment by ywkim312** [comment]
> 
I don't know why. In fact, it is doing the third one since I have pushed it three times. First two passed successfully and running third now. But it takes very very long.

**Comment by ywkim312** [comment]
> Any idea why the pytest is taking so long to install it's dependencies? Seems stuck.

I checked the first one that finished successful, and it took 1h 42m only for setting up the dependencies. It is actually very similar thing that happens when incore-lab is built. Conda installation takes very very long for the github action or docker building unlike the local installation. I don't know why yet...

**Comment by navarroc** [comment]
Do we need a new RC build after these changes?

**Comment by ywkim312** [comment]
> Do we need a new RC build after these changes?

I am building one right now. However, it should be fine without those. I tested in local and will test after using rc one. If the built is successful, then it should work and it should be fine. I will test it anyway.

**Comment by ywkim312** [comment]
> > Do we need a new RC build after these changes?
> 
> I am building one right now. However, it should be fine without those libraires. I tested in local and will test after rc one get built. If the built is successful, then it should work and it should be fine. I will test it anyway.

**Comment by ywkim312** [comment]
> Do we need a new RC build after these changes?

built and published pyincore-data 0.5.1.rc.3. Installation was successful. Tested with pyincore-data example notebook and ran successfully

**Review by nunezco2 — APPROVED** [review]

**Pull request merged**
